version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chargebee-payment-component-nextjs
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: npm run dev
