source 'https://rubygems.org'

gem 'rails'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

# To use debugger
# gem 'debugger'

gem 'chargebee'
gem 'stripe'
gem 'braintree'
